added

diff --git a/.github/workflows/deploy-dev.yaml b/.github/workflows/deploy-dev.yaml
--- a/.github/workflows/deploy-dev.yaml
+++ b/.github/workflows/deploy-dev.yaml
@@ -1008,25 +1008,24 @@ jobs:
 
             echo "Digest     : ${DIGEST}"
 
-            if [[ "${REPOSITORY}" != */* ]]; then
+            # if [[ "${REPOSITORY}" != */* ]]; then
 
-              echo "ERROR: Invalid ECR repository URI for ${SERVICE}."
-
-              exit 1
-
-            fi
-
-            ECR_REPOSITORY="${REPOSITORY}"
-
-            # ECR_REPOSITORY="${REPOSITORY#*/}"
-
-            # if [[ -z "${ECR_REPOSITORY}" ]]; then
-
-            #   echo "ERROR: Unable to determine ECR repository for ${SERVICE}."
+            #   echo "ERROR: Invalid ECR repository URI for ${SERVICE}."
 
             #   exit 1
 
             # fi
+
+            # ECR_REPOSITORY="${REPOSITORY#*/}"
+            ECR_REPOSITORY="${REPOSITORY}"
+
+            if [[ -z "${ECR_REPOSITORY}" ]]; then
+
+              echo "ERROR: Unable to determine ECR repository for ${SERVICE}."
+
+              exit 1
+
+            fi
 
             echo ""
 
